import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Coin98AdapterProvider from "@/app/Coin98AdapterProvider";
import Coin98AdapterModal from "@/app/modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Coin98AdapterProvider>
      {children}
          <Coin98AdapterModal />
      </Coin98AdapterProvider>
      </body>

    </html>
  );
}
